services:
  - type: web
    name: laravel-vite-app
    env: php
    buildCommand: |
      # Cài đặt dependencies
      composer install --optimize-autoloader
      npm install
      npm run build
      php artisan key:generate --force
      php artisan migrate --force
      composer dump-autoload
      php artisan db:seed --force
      php artisan storage:link
    startCommand: /start.sh
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-vite-app.onrender.com
      - key: DB_CONNECTION
        value: mysql
      # Thông tin database từ Railway
      - key: DB_HOST
        value: switchback.proxy.rlwy.net
      - key: DB_PORT
        value: 54387
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: mXIKnFWVTfFwKDETthuwftSnoNhEXxlO
      # Các biến môi trường khác cần thiết
      - key: APP_KEY
        generateValue: true
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync